"""add points column to game_rounds

Revision ID: 6e60d36cfbaf
Revises: 2a41e76b7741
Create Date: 2025-05-25 18:54:20.840487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e60d36cfbaf'
down_revision: Union[str, None] = '2a41e76b7741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'game_rounds',
        sa.Column('points', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rounds', 'points')
    # ### end Alembic commands ###
